import type { Locale } from "../shell/i18n";

const ES = {
  subtitle: "Apaga el incendio de La Cremola",
  description:
    "Apaga el incendio de La Cremola, una urbanización de lujo en Ordino, antes de que se queme entera. Carga agua en el río y suéltala sobre las ventanas en llamas mientras el viento cambia.",
  saved: "SALVADO",
  losses: "PÉRDIDAS",
  water: "AGUA",
  heli: "HELI",
  wind: "VIENTO",
  level: "NIVEL",
  record: "Récord",
  million: "M€",
  decimal: ",",
  dropButton: "AGUA",
  hintRefill: "Baja el cubo al río para cargar agua",
  hintDropKey: "Mantén ESPACIO sobre el fuego para soltar el agua",
  hintDropTouch: "Mantén AGUA sobre el fuego para soltar el agua",
  hintDrag: "ARRASTRA PARA PILOTAR",
  empty: "¡CUBO VACÍO! BAJA AL RÍO",
  smoke: "¡HUMO! EL HELICÓPTERO SE DAÑA",
  levelUp: (n: number) => `NIVEL ${n}: EL FUEGO VA A MÁS`,
  crewArrives: "¡LLEGAN LOS BOMBEROS FRANCESES!",
  supplyArrives: "¡CUBO MÁS GRANDE EN LA CARRETERA!",
  hintSupply: "Toca el camión con el cubo para cambiarlo por uno más grande",
  biggerBucket: "¡Cubo más grande!",
  lostComplex: "La Cremola se ha perdido",
  lostHeli: "El helicóptero ha tenido que aterrizar",
  newRecord: "¡Nuevo récord!",
  savedFlats: (n: number) => (n === 1 ? "1 piso salvado" : `${n} pisos salvados`),
  howTo: "Cómo jugar",
  chipFly: "FLECHAS",
  chipDrag: "ARRASTRA",
  chipDrop: "ESPACIO",
  chipDropTouch: "AGUA",
  chipRiver: "RÍO",
  chipSmoke: "HUMO",
  chipCrew: "BOMBEROS",
  chipSupply: "CAMIÓN",
  helpFly: "Pilota el helicóptero. El cubo cuelga de una cuerda y se balancea.",
  helpDrop: "Suelta el agua sobre las ventanas en llamas. El viento desvía la caída.",
  helpRiver: "Baja el cubo al río para volver a llenarlo.",
  helpSmoke: "El humo sobre el fuego daña el helicóptero. Si se queda sin vida, tiene que aterrizar.",
  helpCrew: "De vez en cuando llegan los bomberos franceses y riegan la primera fila.",
  helpSupply:
    "Un camión trae cubos un poco más grandes: toca el de la caja con el tuyo para cambiarlo. Llegan llenos, pero tardan más en llenarse.",
  helpFooter:
    "El fuego sube de piso en piso y salta a los edificios de al lado, más rápido a favor del viento. Si se quema la mitad del valor de La Cremola, se acabó.",
  helpKeys: "P o Esc: pausa. M: silenciar.",
  oldMen: [
    "¡Ya os lo decía yo!",
    "En mis tiempos esto era un prado",
    "Ahora sí que tienen calefacción",
    "¿Y esto quién lo paga?",
    "Tanta pizarra para esto",
    "Mira, vistas al humo",
    "Mi nieto no podía pagar ni el parking",
    "Esto con las bordas no pasaba",
  ],
  agent: [
    "¡Última unidad disponible!",
    "Ahora con chimenea en cada habitación",
    "Precio rebajado: solo 2,3 M€",
    "Calefacción central incluida",
    "Vistas únicas, a ratos",
    "Acabado ahumado de diseño",
    "¡Visitas guiadas, traigan casco!",
  ],
  crewQuote: "Allez, allez!",
};

export type Texts = typeof ES;

const CA: Texts = {
  subtitle: "Apaga l'incendi de La Cremola",
  description:
    "Apaga l'incendi de La Cremola, una urbanització de luxe a Ordino, abans que es cremi sencera. Carrega aigua al riu i deixa-la anar sobre les finestres en flames mentre el vent canvia.",
  saved: "SALVAT",
  losses: "PÈRDUES",
  water: "AIGUA",
  heli: "HELI",
  wind: "VENT",
  level: "NIVELL",
  record: "Rècord",
  million: "M€",
  decimal: ",",
  dropButton: "AIGUA",
  hintRefill: "Baixa la galleda al riu per carregar aigua",
  hintDropKey: "Mantén ESPAI sobre el foc per deixar anar l'aigua",
  hintDropTouch: "Mantén AIGUA sobre el foc per deixar anar l'aigua",
  hintDrag: "ARROSSEGA PER PILOTAR",
  empty: "GALLEDA BUIDA! BAIXA AL RIU",
  smoke: "FUM! L'HELICÒPTER ES DANYA",
  levelUp: (n: number) => `NIVELL ${n}: EL FOC VA A MÉS`,
  crewArrives: "ARRIBEN ELS BOMBERS FRANCESOS!",
  supplyArrives: "GALLEDA MÉS GRAN A LA CARRETERA!",
  hintSupply: "Toca el camió amb la galleda per canviar-la per una de més gran",
  biggerBucket: "Galleda més gran!",
  lostComplex: "La Cremola s'ha perdut",
  lostHeli: "L'helicòpter ha hagut d'aterrar",
  newRecord: "Nou rècord!",
  savedFlats: (n: number) => (n === 1 ? "1 pis salvat" : `${n} pisos salvats`),
  howTo: "Com jugar",
  chipFly: "FLETXES",
  chipDrag: "ARROSSEGA",
  chipDrop: "ESPAI",
  chipDropTouch: "AIGUA",
  chipRiver: "RIU",
  chipSmoke: "FUM",
  chipCrew: "BOMBERS",
  chipSupply: "CAMIÓ",
  helpFly: "Pilota l'helicòpter. La galleda penja d'una corda i es gronxa.",
  helpDrop: "Deixa anar l'aigua sobre les finestres en flames. El vent desvia la caiguda.",
  helpRiver: "Baixa la galleda al riu per tornar-la a omplir.",
  helpSmoke: "El fum sobre el foc danya l'helicòpter. Si es queda sense vida, ha d'aterrar.",
  helpCrew: "De tant en tant arriben els bombers francesos i reguen la primera fila.",
  helpSupply:
    "Un camió porta galledes una mica més grans: toca la de la caixa amb la teva per canviar-la. Arriben plenes, però triguen més a omplir-se.",
  helpFooter:
    "El foc puja de pis en pis i salta als edificis del costat, més ràpid a favor del vent. Si es crema la meitat del valor de La Cremola, s'ha acabat.",
  helpKeys: "P o Esc: pausa. M: silenciar.",
  oldMen: [
    "Ja us ho deia jo!",
    "En el meu temps això era un prat",
    "Ara sí que tenen calefacció",
    "I això qui ho paga?",
    "Tanta pissarra per a això",
    "Mira, vistes al fum",
    "El meu nét no podia pagar ni el pàrquing",
    "Això amb les bordes no passava",
  ],
  agent: [
    "Última unitat disponible!",
    "Ara amb llar de foc a cada habitació",
    "Preu rebaixat: només 2,3 M€",
    "Calefacció central inclosa",
    "Vistes úniques, de tant en tant",
    "Acabat fumat de disseny",
    "Visites guiades, porteu casc!",
  ],
  crewQuote: "Allez, allez!",
};

const EN: Texts = {
  subtitle: "Put out the fire at La Cremola",
  description:
    "Put out the fire at La Cremola, a luxury development in Ordino, before it burns to the ground. Fill up at the river and drop the water on the burning windows while the wind keeps changing.",
  saved: "SAVED",
  losses: "LOSSES",
  water: "WATER",
  heli: "HELI",
  wind: "WIND",
  level: "LEVEL",
  record: "Best",
  million: "M€",
  decimal: ".",
  dropButton: "WATER",
  hintRefill: "Dip the bucket in the river to fill it",
  hintDropKey: "Hold SPACE over the fire to drop the water",
  hintDropTouch: "Hold WATER over the fire to drop the water",
  hintDrag: "DRAG TO FLY",
  empty: "BUCKET EMPTY! BACK TO THE RIVER",
  smoke: "SMOKE! THE HELICOPTER IS TAKING DAMAGE",
  levelUp: (n: number) => `LEVEL ${n}: THE FIRE GETS WORSE`,
  crewArrives: "FRENCH FIREFIGHTERS ARRIVE!",
  supplyArrives: "BIGGER BUCKET ON THE ROAD!",
  hintSupply: "Touch the truck with your bucket to swap it for a bigger one",
  biggerBucket: "Bigger bucket!",
  lostComplex: "La Cremola is lost",
  lostHeli: "The helicopter had to land",
  newRecord: "New record!",
  savedFlats: (n: number) => (n === 1 ? "1 flat saved" : `${n} flats saved`),
  howTo: "How to play",
  chipFly: "ARROWS",
  chipDrag: "DRAG",
  chipDrop: "SPACE",
  chipDropTouch: "WATER",
  chipRiver: "RIVER",
  chipSmoke: "SMOKE",
  chipCrew: "FIREFIGHTERS",
  chipSupply: "TRUCK",
  helpFly: "Fly the helicopter. The bucket hangs from a rope and swings.",
  helpDrop: "Drop the water on the burning windows. The wind pushes it sideways.",
  helpRiver: "Dip the bucket in the river to fill it again.",
  helpSmoke: "Smoke above the fire damages the helicopter. If it runs out of health, it has to land.",
  helpCrew: "Every now and then the French firefighters arrive and hose down the front row.",
  helpSupply:
    "A truck brings slightly bigger buckets: touch the one on its bed with yours to swap. They come full, but take longer to fill.",
  helpFooter:
    "Fire climbs from floor to floor and jumps to the next buildings, faster downwind. If half of La Cremola's value burns, it's over.",
  helpKeys: "P or Esc: pause. M: mute.",
  oldMen: [
    "I told you so!",
    "In my day this was a meadow",
    "Now they finally have heating",
    "And who's paying for this?",
    "All that slate for this",
    "Look, smoke views",
    "My grandson couldn't even afford the parking",
    "This never happened with the old barns",
  ],
  agent: [
    "Last unit available!",
    "Now with a fireplace in every room",
    "Price cut: only 2.3 M€",
    "Central heating included",
    "Unique views, now and then",
    "Designer smoked finish",
    "Guided tours, bring a helmet!",
  ],
  crewQuote: "Allez, allez!",
};

/** Every string the game shows, in each language. */
export const TEXT: Record<Locale, Texts> = { es: ES, ca: CA, en: EN };

/** In-world signs are in Catalan, like the real ones. */
export const BILLBOARD = { name: "LA CREMOLA", line: "RESIDENCIAL · DES DE 2,4 M€" };

/** Thousands of euros as millions with one decimal: 12400 -> "12,4 M€". */
export const formatMillions = (t: Texts, thousands: number) =>
  `${(thousands / 1000).toFixed(1).replace(".", t.decimal)} ${t.million}`;
